import type { Book } from "@/lib/types";

export const books: Omit<Book, "id">[] = [
  {
    title: "THE CREATIVE ACT",
    author: "RUBIN",
    stars: 4,
    bgColor: "#1d1d2b",
    textColor: "text-white",
    width: 54,
    height: 360,
    titleSize: "text-[13px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-widest",
  },
  {
    title: "NO MORE MR. NICE GUY",
    author: "GLOVER",
    stars: 3,
    bgColor: "#f8b486",
    textColor: "text-slate-800",
    width: 42,
    height: 310,
    titleSize: "text-[11px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "YELLOWFACE",
    author: "KUANG",
    stars: 4,
    bgColor: "#fedc7f",
    textColor: "text-slate-900",
    starColor: "text-yellow-600",
    width: 54,
    height: 340,
    titleSize: "text-[13px]",
    titleWeight: "font-black",
    titleTracking: "tracking-widest",
  },
  {
    title: "THE SILENT PATIENT",
    author: "MICHAELIDES",
    stars: 3,
    bgColor: "#3e6080",
    textColor: "text-white",
    width: 48,
    height: 335,
    titleSize: "text-[12px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-widest",
  },
  {
    title: "ALICE'S ADVENTURES IN WONDERLAND",
    author: "CARROLL",
    stars: 3,
    bgColor: "#4fa987",
    textColor: "text-white/90",
    width: 44,
    height: 335,
    titleSize: "text-[10px]",
    titleWeight: "font-medium",
    titleTracking: "tracking-tight",
  },
  {
    title: "THE GENTLEMAN FROM PERU",
    author: "ACIMAN",
    stars: 3,
    bgColor: "#ff4d4d",
    textColor: "text-white",
    width: 20,
    height: 260,
    titleSize: "text-[9px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tighter",
  },
  {
    title: "THE BOOK OF CLARITY",
    author: "CHOPRA",
    stars: 4,
    bgColor: "#7fa05a",
    textColor: "text-slate-100",
    width: 40,
    height: 285,
    titleSize: "text-[12px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "BEFORE THE COFFEE GETS COLD",
    author: "KAWAGUCHI",
    stars: 4,
    bgColor: "#3b4b2a",
    textColor: "text-stone-200",
    width: 36,
    height: 285,
    titleSize: "text-[10px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "THE HARD THING ABOUT HARD THINGS",
    author: "HOROWITZ",
    stars: 4,
    bgColor: "#f7b76e",
    textColor: "text-slate-800",
    width: 46,
    height: 310,
    titleSize: "text-[11px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "GHACHAR GHOCHAR",
    author: "SHANBHAG",
    stars: 3,
    bgColor: "#fef5d6",
    textColor: "text-slate-800",
    starColor: "text-yellow-600",
    width: 34,
    height: 265,
    titleSize: "text-[11px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "TINY EXPERIMENTS",
    author: "CUNFF",
    stars: 4,
    bgColor: "#002a46",
    textColor: "text-white",
    width: 50,
    height: 340,
    titleSize: "text-[13px]",
    titleWeight: "font-black",
    titleTracking: "tracking-[0.2em]",
  },
  {
    title: "PIRANESI",
    author: "CLARKE",
    stars: 3,
    bgColor: "#d72131",
    textColor: "text-white",
    width: 44,
    height: 320,
    titleSize: "text-[13px]",
    titleWeight: "font-black",
    titleTracking: "tracking-widest",
  },
  {
    title: "WHITE NIGHTS",
    author: "DOSTOEVSKY",
    stars: 4,
    bgColor: "#f89b21",
    textColor: "text-slate-800",
    width: 42,
    height: 320,
    titleSize: "text-[11px]",
    titleWeight: "font-black",
    titleTracking: "tracking-tight",
  },
  {
    title: "V FOR VENDETTA",
    author: "MOORE",
    stars: 3,
    bgColor: "#fecb4d",
    textColor: "text-slate-900",
    starColor: "text-orange-700",
    width: 50,
    height: 340,
    titleSize: "text-[14px]",
    titleWeight: "font-black",
    titleTracking: "tracking-widest",
  },
  {
    title: "OF MICE AND MEN",
    author: "STEINBECK",
    stars: 4,
    bgColor: "#8e54e9",
    textColor: "text-white",
    width: 34,
    height: 285,
    titleSize: "text-[10px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "THE HOUSEKEEPER AND THE PROFESSOR",
    author: "OGAWA",
    stars: 5,
    bgColor: "#6eb7ff",
    textColor: "text-white",
    width: 40,
    height: 330,
    titleSize: "text-[10px]",
    titleWeight: "font-medium",
    titleTracking: "tracking-tight",
  },
  {
    title: "THE MEMORY POLICE",
    author: "OGAWA",
    stars: 4,
    bgColor: "#ff1a7f",
    textColor: "text-white",
    width: 46,
    height: 335,
    titleSize: "text-[12px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-widest",
  },
  {
    title: "HATCHING TWITTER",
    author: "BILTON",
    stars: 4,
    bgColor: "#ffcc33",
    textColor: "text-slate-800",
    starColor: "text-orange-600",
    width: 48,
    height: 335,
    titleSize: "text-[13px]",
    titleWeight: "font-black",
    titleTracking: "tracking-widest",
  },
  {
    title: "THE FALL",
    author: "CAMUS",
    stars: 4,
    bgColor: "#004b66",
    textColor: "text-white",
    width: 34,
    height: 280,
    titleSize: "text-[11px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-widest",
  },
  {
    title: "HOLES",
    author: "SACHAR",
    stars: 3,
    bgColor: "#40c4cc",
    textColor: "text-slate-900",
    width: 46,
    height: 310,
    titleSize: "text-[15px]",
    titleWeight: "font-black",
    titleTracking: "tracking-[0.3em]",
  },
  {
    title: "BLACK EDGE",
    author: "KOLHATKAR",
    stars: 5,
    bgColor: "#f89021",
    textColor: "text-slate-900",
    width: 46,
    height: 335,
    titleSize: "text-[13px]",
    titleWeight: "font-black",
    titleTracking: "tracking-widest",
  },
  {
    title: "COMPANY OF ONE",
    author: "JARVIS",
    stars: 4,
    bgColor: "#70647a",
    textColor: "text-white/80",
    width: 50,
    height: 310,
    titleSize: "text-[11px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-widest",
  },
  {
    title: "GRIEF IS THE THING WITH FEATHERS",
    author: "PORTER",
    stars: 3,
    bgColor: "#e19a9a",
    textColor: "text-slate-900",
    width: 34,
    height: 260,
    titleSize: "text-[9px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-tight",
  },
  {
    title: "THE HOUSEMAID'S SECRET",
    author: "MCFADDEN",
    stars: 4,
    bgColor: "#1d1d2b",
    textColor: "text-white",
    width: 50,
    height: 330,
    titleSize: "text-[12px]",
    titleWeight: "font-bold",
    titleTracking: "tracking-widest",
  },
];
